### ISSUE TITLE
Please continue this Project

### ISSUE THREAD

**Issue by furesoft** [rzubek/CSLisp#1]
Please add more lib functions like structs

**Comment by rzubek** [comment]
Hey, thank you! Just the motivation I needed :)

**Comment by furesoft** [comment]
i could help you if you want

**Comment by rzubek** [comment]
That sounds intriguing. What do you have in mind? (Help as an end user, as a developer, documentation, etc?)

Also can you say more about the structs comment - what kind of functionality do you find yourself wanting?

**Comment by furesoft** [comment]
i want to help as developer. 

a struct procedure that generates 2 general functions:

(make-struct point '(x y))

(point? instance)
(make-point 1 2)

and some setters and getters

(set-x! instance value)
(set-y! instance value)

(get-x instance)
(get-y instance)

**Comment by furesoft** [comment]
and we should implement very basic functions and structures like for math operations and put it in different packages

**Comment by furesoft** [comment]
And we need some basic functions like apply

**Comment by furesoft** [comment]
and the possiblity to import clr class:

(import-clr-object 'System.Console)

(Console-WriteLine "hello world")

(make-Random)

**Comment by rzubek** [comment]
That sounds cool!

`apply` would probably be the fastest, i suspect it's doable as a little macro. Would you like to take a stab at it? (In which case let's open a new issue for tracking.)

Adding more standard libraries, and especially structs sound great too. One idea for structs would be to port something like SRFI-9 (but because the macro system is different it would probably be a rewrite). Unless you have a different implementation idea!

And as for CLR interop, that's already in progress! I was waiting with documenting it until it's further along, but maybe I should document it now so that the API can be discussed.

**Comment by furesoft** [comment]
do you have gitter? it is easier to communicate in a chat

**Comment by rzubek** [comment]
I'm not on gitter, but we can stick to github for now - I enabled Discussions on this project in case that's more convenient.

And thanks for opening up the two new issues, I'll switch over to those and close this one!
